services:
  # Application BennesPro
  app:
    build: .
    container_name: bennespro_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://remondis_db:Remondis60110$@postgres:5432/remondis_db
      - JWT_SECRET=85eb00206d3991c2ade3186cfad4e9265fc9d72cadbe698ba305884086bc3e29e5d11f92df517a684f4e4bd136507bb81b6ef79902e5eb96d98273f6c9bb1723
      - SESSION_SECRET=f6b3e76ee636d248b8c85091425ae4fe9de4a8011b1fa17d30f0fcf13f5c2df2b5a5c1c4109dd6b8c5e22eaae33feb872434e71cc2f17f64a3b4e72d40e2d4f5
    depends_on:
      - postgres
    networks:
      - bennespro_network

  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bennespro_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: remondis_db
      POSTGRES_USER: remondis_db
      POSTGRES_PASSWORD: Remondis60110$
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - bennespro_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bennespro_redis
    restart: unless-stopped
    command: redis-server --requirepass Remondis60110$
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bennespro_network

networks:
  bennespro_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local