#!/bin/bash

echo "🔥 SOLUTION FINALE VPS - ON NETTOIE TOUT"
echo "========================================"
echo ""
echo "COPIER-COLLER CES COMMANDES SUR VOTRE VPS:"
echo ""
echo "# 1. CONNEXION VPS"
echo "ssh root@purpleguy.world"
echo ""
echo "# 2. ARRÊT BRUTAL"
echo "systemctl stop nginx"
echo "pm2 kill"
echo "pkill -9 -f node"
echo ""
echo "# 3. DESTRUCTION TOTALE"
echo "cd /var/www/bennespro"
echo "rm -rf dist/"
echo "rm -rf .next/"
echo "rm -rf build/"
echo "rm -rf public/"
echo "rm -rf node_modules/.vite"
echo "rm -rf node_modules/.cache"
echo ""
echo "# 4. CRÉATION FICHIER ANTI-STRIPE"
echo "mkdir -p client/src/lib"
echo "cat > client/src/lib/stripe.js << 'EOF'"
echo "export default null;"
echo "EOF"
echo ""
echo "# 5. BUILD PROPRE PAYPLUG"
echo "export NODE_ENV=production"
echo "export VITE_PAYPLUG_PUBLIC_KEY=pk_test_2wDsePkdatiFXUsRfeu6m1"
echo "npm run build"
echo ""
echo "# 6. NETTOYAGE POST-BUILD"
echo "find dist -name '*.js' -exec sed -i 's/VITE_STRIPE_PUBLIC_KEY/VITE_PAYPLUG_PUBLIC_KEY/g' {} +"
echo "find dist -name '*.js' -exec sed -i 's/js.stripe.com/js.payplug.com/g' {} +"
echo ""
echo "# 7. NGINX SANS BULLSHIT"
echo "cat > /etc/nginx/sites-available/bennespro << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    listen 443 ssl http2;"
echo "    server_name purpleguy.world;"
echo "    "
echo "    root /var/www/bennespro/dist/public;"
echo "    "
echo "    # NO STRIPE CSP"
echo "    add_header Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.payplug.com https://secure.payplug.com https://api.payplug.com https://maps.googleapis.com https://maps.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://api.payplug.com https://secure.payplug.com https://maps.googleapis.com wss: ws:;\" always;"
echo "    "
echo "    location / {"
echo "        try_files \$uri /index.html;"
echo "    }"
echo "    "
echo "    location /api {"
echo "        proxy_pass http://127.0.0.1:5000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "    }"
echo "}"
echo "EOF"
echo ""
echo "# 8. RESTART TOUT"
echo "nginx -t && systemctl restart nginx"
echo "pm2 start ecosystem.config.cjs --name bennespro"
echo "pm2 save"
echo ""
echo "# 9. CLEAR CACHE NAVIGATEUR"
echo "# Dire aux utilisateurs de faire CTRL+F5 sur purpleguy.world"
echo ""
echo "✅ C'EST TOUT. PAS DE REPLIT, PAS DE STRIPE, QUE DU PAYPLUG."