#!/bin/bash

# NETTOYAGE NUCLÉAIRE VPS PRODUCTION
echo "🔥 NETTOYAGE NUCLÉAIRE VPS UBUNTU - ON ARRÊTE DE RIGOLER"
echo "========================================================"

# COMMANDES À EXÉCUTER DIRECTEMENT SUR VOTRE VPS UBUNTU
# SSH into your VPS first: ssh user@purpleguy.world

echo "1. ARRÊT TOTAL DES SERVICES"
echo "============================"
echo "sudo systemctl stop nginx"
echo "sudo systemctl stop bennespro"
echo "sudo pm2 stop all"
echo "sudo pkill -f node"
echo ""

echo "2. DESTRUCTION TOTALE DES ANCIENS BUILDS"
echo "========================================"
echo "cd /var/www/bennespro"
echo "sudo rm -rf dist/"
echo "sudo rm -rf node_modules/.cache"
echo "sudo rm -rf .vite"
echo "sudo rm -rf build/"
echo "sudo rm -rf public/"
echo ""

echo "3. NETTOYAGE DU CACHE NGINX"
echo "==========================="
echo "sudo rm -rf /var/cache/nginx/*"
echo "sudo rm -rf /etc/nginx/sites-enabled/default"
echo ""

echo "4. BUILD PROPRE SANS STRIPE"
echo "==========================="
echo "# Créer le fichier stripe.js bloquant"
echo "sudo mkdir -p client/src/lib"
echo "sudo tee client/src/lib/stripe.js << 'EOF'"
echo "// STRIPE COMPLÈTEMENT DÉSACTIVÉ"
echo "export const stripe = null;"
echo "export const loadStripe = () => null;"
echo "export default null;"
echo "EOF"
echo ""
echo "# Build de production"
echo "sudo NODE_ENV=production npm run build"
echo ""

echo "5. CONFIGURATION NGINX PROPRE"
echo "============================="
echo "sudo tee /etc/nginx/sites-available/bennespro << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name purpleguy.world www.purpleguy.world;"
echo "    root /var/www/bennespro/dist/public;"
echo "    index index.html;"
echo ""
echo "    # Security headers"
echo "    add_header X-Frame-Options DENY;"
echo "    add_header X-Content-Type-Options nosniff;"
echo "    add_header X-XSS-Protection \"1; mode=block\";"
echo "    add_header Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.payplug.com https://secure.payplug.com https://api.payplug.com https://maps.googleapis.com https://maps.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.payplug.com https://secure.payplug.com https://maps.googleapis.com wss: ws:; font-src 'self' https://fonts.gstatic.com;\";"
echo ""
echo "    location / {"
echo "        try_files \$uri \$uri/ /index.html;"
echo "    }"
echo ""
echo "    location /api {"
echo "        proxy_pass http://localhost:5000;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Upgrade \$http_upgrade;"
echo "        proxy_set_header Connection 'upgrade';"
echo "        proxy_set_header Host \$host;"
echo "        proxy_cache_bypass \$http_upgrade;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "6. REDÉMARRAGE PROPRE"
echo "===================="
echo "sudo ln -sf /etc/nginx/sites-available/bennespro /etc/nginx/sites-enabled/"
echo "sudo nginx -t"
echo "sudo systemctl restart nginx"
echo "sudo pm2 start ecosystem.config.cjs"
echo "sudo pm2 save"
echo "sudo pm2 startup"
echo ""

echo "7. VÉRIFICATION FINALE"
echo "====================="
echo "curl -I https://purpleguy.world"
echo "curl https://purpleguy.world/api/health"
echo ""

echo "✅ COPIER-COLLER CES COMMANDES DIRECTEMENT SUR VOTRE VPS"
echo "========================================================="